{% set name = "itables" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itables-{{ version }}.tar.gz
  sha256: 771541157cec9fe2169aae320b77146a4d2ce6e073e92850527c611d4a9aa2d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - requests
    - setuptools
  run:
    - ipython
    - pandas
    - python >=3.6

test:
  imports:
    - itables
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mwouts/itables
  summary: Interactive Tables in Jupyter
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_jquery.txt

extra:
  recipe-maintainers:
    - asford
