{% set name = "itables" %}
{% set version = "1.5.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itables-{{ version }}.tar.gz
  sha256: 68b15240038dc6c7b136780f6889b61cead7325b472638226ba4b4fc34c9614c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - requests
    - setuptools
  run:
    - ipython
    - pandas
    - numpy
    - python >=2.7

test:
  imports:
    - itables
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mwouts/itables
  summary: Interactive Tables in Jupyter
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_jquery.txt

extra:
  recipe-maintainers:
    - mwouts
    - asford
