{% set name = "itables" %}
{% set version = "0.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itables-{{ version }}.tar.gz
  sha256: dea7996cb4833a00867ad6e94a084cc5ad9a470471a0aaec9c82d4b53ab71a23

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipython
    - pandas
    - python >=3.6

test:
  imports:
    - itables
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mwouts/itables
  summary: Interactive Tables in Jupyter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
