{% set name = "itables" %}
{% set version = "0.4.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itables-{{ version }}.tar.gz
  sha256: b74e4090ebd9dfb5d44b1e040d835f9162f593aff11b4b82d3ac43f3a2c754ea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipython
    - pandas
    - python >=3.6

test:
  imports:
    - itables
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mwouts/itables
  summary: Interactive Tables in Jupyter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
